### ISSUE TITLE
Scraper: Multiple of the same restaurant in output

### ISSUE THREAD

**Issue by theusaf** [tobyloki/BeaverEats#1]
**Issue**:
The output only contains items for *Bing's Cafe*, rather than all the restaurants.

**Comment by tobyloki** [comment]
Output should now show all restaurant generic information as of commit https://github.com/tobyloki/BeaverEats/tree/2fb0ec0f2504342809fe5c5b9b2e16026905f788. Some menus are empty b/c it's in development since different restaurant menu pages may have different html structures.
