### ISSUE TITLE
Dining Calendar API: Can contain duplicate restaurant information

### ISSUE THREAD

**Issue by theusaf** [tobyloki/BeaverEats#2]
This API (https://my.uhds.oregonstate.edu/api/dining/calendar) contains "duplicate" items.

For example, `East Side Eats` has multiple instances in the data. This is in order to separate multiple kinds of hours:
* 07:00 - 10:00
* 11:00 - 14:00
* 17:00 - 19:00
* etc.

**Comment by tobyloki** [comment]
Fixed in commit: https://github.com/tobyloki/BeaverEats/commit/393994764b6113fa5add68b74f62bd6d8a2b2cd5. When hours are closed though, the start/end hours are null.
