### ISSUE TITLE
Scraper: Restaurant sometimes doesn't have menu items

### ISSUE THREAD

**Issue by theusaf** [tobyloki/BeaverEats#3]
See output below:
```json
{
  "location": "Weatherford Hall",
  "name": "Bing's Cafe",
  "url": "https://uhds.oregonstate.edu/restaurants/bings-cafe",
  "diningDollars": 1,
  "start": null,
  "end": null,
  "menu": []
}
```

**Comment by tobyloki** [comment]
This is now fixed as of commit https://github.com/tobyloki/BeaverEats/tree/c2a8f5063b7826efe92b4a005bc50ae42ce8540f with the exception of 5 restaurants like Panda, Togos, 1 restaurant with a broken url, and 2 restaurants with no menu items.
